export { credentialsSchema } from "./system";

export {
  stringIdSchema,
  hospitalIdSchema,
  userIdSchema,
  hospitalSchema,
  hospitalUpdateSchema,
  departmentSchema,
  departmentUpdateSchema,
  adminSchema,
  adminUpdateSchema,
  userSchema,
  userUpdateSchema,
  doctorSchema,
  doctorUpdateSchema,
  appointmentSchema,
  appointmentUpdateSchema,
  textSchema,
  textUpdateSchema,
  recordSchema,
  recordUpdateSchema,
  subscriptionInfoSchema,
  subscriptionInfoUpdateSchema,
} from "./database";
